sudo: false
language: c

addons:
  apt:
    packages:
    - pandoc

branches:
  only:
  - /^\d+\.\d+(\.\d+)?(-\S*)?$/

env:
  global:
  - secure: DYg9yivS2/M7lN5VQw2TU0UTsIK+nQDYGpdjutQdudDfVlc5JAqtkLdYnsenVcFV5JziAztglwXWeftiAU4/O9FRJvPh7+hLAt0KVQsnVzilbKdcglo88X9GRaXlitodqioRoGawyDmWLzxZMn1l74UtyZPUxbfwsqQbXCcG2hYft8kXe0ch+b1XNoBS/zuA8A9WcB8CcjUw33F11Nvl4kg+Czkeeivt87z+/uuhF28Ha2jK7tw8E/M18w8RGL3smNzDhiNphtotueWq8dY839oZn3vaIwb3uOWHmGDMFjx4kT+JxsERAL18Hs3SBSjCMysoILQvHM7yUg+gtfm3CYQlzkcT+8/mJCTy7GN2i10ABcFrqDKugbS7SlJTN4p/zzHiz4XjRAUC/GXHl97I1zex/WOxfmEqdE1j2Dc/+Du+ZfMQWwU08xqvYH5jt4jr/sbyDeXVciuCqEJMZcXuJS4PTd7sAyw7vkI5fOAzqq2sAqBLwwFjDnOzDX6AiTJdG6QB9n5EPPX4R/2Wkj1zwTI2hNQsoS7OdlYaOkN6pPhGlWoNLGujtgUfFhEIy8hM7CNB5UNwm4F8gBtRfqztrj5KwqN2zg/C9BnsJ8QtKS20dY6ATzkKrkALyT2EDpzBkGjKxnk4MzuvPgd0MnHN1ycewjAgHUTUuVT8dAv0dRo=
  - secure: XM6QHjZEHork3bPeeryf2ljcjEhHFWE2iPV+icGpwrbIJ5plpnghV0/LpYEh5MsCzgK4Kizafwot+evQlyJ7fCgpFIrWdmvMgm/JolD/18zDzxa0tCs6OHlNuE8wa5kfwnG0j4hAgXRAMhuFIfkaEzl3wnmjGH/nMqmdP0FwgBIApPvmwrv4shohKb3/QPaXR297MF6IFqDJgMLRrqDQ4d4OMl830rz77SFcHZw2Cats+0Vx6s7yHE3Lx3BjJOcAM4ZmfOgh7/tKnIIh3O1cttxDIi5pZ81pe9/e11AyklLfsbDaqmTqlaV2kPOsVvS1fkBxcV+wTjsiLAWTXy0aQj2zG4hWvHpjf4JNQpWBLfRb4em5zGvtciqoX2Nc2AM+F32QmO/Nl8mRVClXMq4OOBSMq1yBy+jU8qJnG9UbGQteQEqPDSIX6pvWuCyY9sMl35qGAT+pzL4XrjnTn5f2stOVFY2NL0aUBlEOXlwmmlsTsY2C2cJNFKUxbEtfpIuwvNkV55TbR7x1KAc92mF96Scvjn7FnERTyAQSdmoswo30lfQB6SB8G70Mv6Wz7Gws7U63KpjHtVH1EaU8vWZn89z46DmhGi2MguEOmqxV+VfVUWkeF57CKii7owfdpPlyeuj8l+3a49+kg7BiN9SSXnSIirzAKAh3HoGIdONnVUo=

script: curl -s https://raw.githubusercontent.com/oUF-wow/packager/master/release.sh | bash

notifications:
  email:
    on_success: always
    on_failure: always
    recipients:
      secure: qb6NVgpHDQzXV9VfZjipxwLnCXe4GtSboBKopqK6VI+cCGSFCivASGuL95lzVw3XErI/42FXc5ztd5UmOfhygxbHGA249LqF1k9wG2LWmsPngwXoBSYHsBqbrYgYWk82p4rETfshYlmSQDg73DotLYlIHp7IViwcrU5Bv+lyQPf+Uq3ctCfr2uoVZrB2nVronz14L+WIaTN0P3jOObNAspkctLkGlfxVdwB1lUUF6rsvMl4VQBLDUvbTDcCdLr8FFonpJcU5wWidTFDuSy3v7qQ0nQm4TF9mhzVVE754H8znKBfO6XBTtbWKriaLOKj7HyfZzrNwmpzghkOpdtkpgC6dKGvZlkKvYn5bUXf+ZKBXwGxHM5PMnC/vJvQo3NzNt6UGjkgSsw6VnBltOeqonAf1O+jUzNr0YinK5YEDB3D2VZExylpl8rdVjoUYQaC7l+qBADjTmJcSC1o0W+I0Z1ebkGXutc2CScc+mSJn+mU2lyFOkAy28ZMLgVmXJbDwRmO5eemUhI0vPvOFC6EaYCHqzrtQjcf86+Ms07ae3Xp17X/m2XcRfM5R6i6ZXXUD+K3LIvD6R6Jym04E3vBahpeJMucM0in3ECCqjtVWW6C3eT48CLn7zrHj8YwiTl3Kx/4ZWEKnTWa22UC4ocNaUTxQDsw3jSn6X+cZj5RA4uU=
